### ISSUE TITLE
Change Backend to new smart contract

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/BackEnd#48]
### Todo
- [ ] Use real ABI from new contract
- [ ] Set contract address of new contract
- [ ] Change documentation to "Agorex"
